version: 2.1

orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
  gcr: circleci/gcp-gcr@0.8

jobs:

  build:
    description: Build static app image using gcp orb
    machine: true
    steps:
      - checkout
      - gcr/build-image:
          image: dehla-pakad-ui-${CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)
          tag: latest
      - gcr/gcr-auth
      - gcr/push-image:
          image: dehla-pakad-ui-${CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)
          tag: latest

  push:
    description: Push to google container registry
    machine: true
    steps:
      - gcp-gke/install
      - gcp-gke/init
      - gcp-gke/rollout-image:
          cluster: eightbitguy
          container: ui-container
          deployment: ui-app-deployment
          image: gcr.io/my-cluster-290007/dehla-pakad-api-${CIRCLE_BRANCH}-$(echo $CIRCLE_SHA1 | cut -c -7)


workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - push:
          requires:
            - build
